<?php
    if ($flash==true)
    {?> 
        <div class="alert alert-success alert-dismissable col-lg-12">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <?php 
        $set = $req->showFlash();
        ?>  
        </div> 
    <?php }
?>

<body>
    <div class="container">
        <header class="page-header">
            <h1>How she did</h1>
        </header>

        <section class="row">
        <div class="col-sm-12">


        <p><a href ="index.php"> Retour à la liste des articles </a></p>

        <br><br>
        <h2> Mes articles </h2>
        <?php
        while ($data=$articles-> fetch())
        {
        ?>
        
            <section class="col-sm-offset-1 col-sm-8 table-responsive">
                <table class="table table-bordered table-striped table-condensed">
                <tr>
                    <td>
                    <?php echo $data['title']; ?>
                    </td>

                    <td>
                    le <?=$data['article_date_fr']; ?>
                    </td>

                    <td>
                    <form action="index.php?action=editArticle&amp;id=<?= $data['id'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-info"><span class="glyphicon glyphicon-pencil"></span> Modifier</button>
                    </form></td>

                    <td><form action="index.php?action=removeArticle&amp;id=<?= $data['id'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span> Supprimer</button>
                    </form></td>
                </tr>
                </table>
            </section>

        <?php
        }
        $articles->closeCursor();
        ?>
        <br>
            <section class="col-sm-10">
                <h2 class="ajout"> Ajouter un nouvel article </h2>

                <form action='index.php?action=addArticle' method='post' enctype='multipart/form-data'>
                    
                <div>
                    <label for="title">Titre chapitre</label><br />
                    <input type="text" id="title" name="title">
                </div>
                <div>
                    <label for="content">Texte</label><br />
                    <textarea id="#mytextarea" name="content"></textarea>
                </div>
                <div>
                    <label for="file">Fichier (tous formats | max. 1 Mo) :</label><br />
                    <input type="file" name="file" id="file" /><br />
                </div>
                <div>
                    <label for="file">Fichier (tous formats | max. 1 Mo) :</label><br />
                    <input type="file" name="file2" id="file2" /><br />
                </div> 
                <div>
                    <button class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-floppy-saved"></span> Enregistrer</button>
                </div>
                </form>
            </section>
        </br>
        <br><br>
        <section class="row">
        <div class="col-sm-12">
        <h2> Mes articles de ma trousse </h2>
        
            <ul class="nav nav-pills col-sm-11">
        <li class="active"><a data-toggle="pill" href="#soin_visage" id="visage">Soin visage</a></li>
        <li><a data-toggle="pill" href="#soin_corp" id="corp">Soin corp</a></li>
        <li><a href="#">Make-up teint</a></li>
        <li><a href="#">Make-up yeux</a></li>
        <li><a href="#">Make-up levre</a></li>
    </ul>
<div class="pill-content col-sm-11">  
    <div id="soin_visage" class="col-sm-12 pill-pane fade in active text-center" style="margin-right: 15px; margin-top: 15px; margin-bottom: 15px">
    <?php
    $datas1=$articlesTrousseSoinVisage-> fetchAll();
    foreach ($datas1 as $data)    
    { ?>
        <div class="col-sm-12 text-center" style="margin-right: 15px; margin-top: 15px; margin-bottom: 15px">
            <div class="col-sm-2">
                <?php
                if($data['file_article_trousse']){
                    echo '<img src="images/'.$data['file_article_trousse'].'" class="image3 width-100" alt="image" style="position:relative"/>';
                } 
                ?> 
                </br>
            </div>
            <div class="col-sm-9">
                <strong>
                <span class="pull-left">
                    <?php
                    echo $data['title_article_trousse']; ?>
                </span>
                </strong>
                </br>
                <form action="index.php?action=editArticleTrousse&amp;id=<?= $data['id_article_trousse'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-info"><span class="glyphicon glyphicon-pencil"></span> Modifier</button>
                </form>
                <form action="index.php?action=removeArticleTrousse&amp;id=<?= $data['id_article_trousse'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span> Supprimer</button>
                </form>
            </div>        
        </div>
    <?php }
    $articlesTrousseSoinVisage->closeCursor(); ?>
    </div>
    
    <div id="soin_corp" class="col-sm-12 pill-pane fade text-center" style="margin-right: 15px; margin-top: 15px; margin-bottom: 15px">
    <?php
    $articlesSoinCorp=$articlesTrousseSoinCorp-> fetchAll();
    foreach ($articlesSoinCorp as $data1)    
    { ?>
        <div class="col-sm-12 text-center" style="margin-right: 15px; margin-top: 15px; margin-bottom: 15px">
            <div class="col-sm-2">
                <?php
                if($data1['file_article_trousse']){
                    echo '<img src="images/'.$data1['file_article_trousse'].'" class="image3 width-100" alt="image" style="position:relative"/>';
                } 
                ?> 
                </br>
            </div>
            <div class="col-sm-9">
                <strong>
                <span class="pull-left">
                    <?php
                    echo $data1['title_article_trousse']; ?>
                </span>
                </strong>
                </br>
                <form action="index.php?action=editArticleTrousse&amp;id=<?= $data1['id_article_trousse'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-info"><span class="glyphicon glyphicon-pencil"></span> Modifier</button>
                </form>
                <form action="index.php?action=removeArticleTrousse&amp;id=<?= $data1['id_article_trousse'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span> Supprimer</button>
                </form>
            </div>        
        </div>
    <?php }
    $articlesTrousseSoinCorp->closeCursor();
    ?>
    </div> 
 </div>   
    </br>
    
        </br>
            <section class="col-sm-10">
                <h2 class="ajout"> Ajouter un article dans ma trousse </h2>

                <form action='index.php?action=addArticleTrousse' method='post' enctype='multipart/form-data'>
                    
                <div>
                    <label for="title">Titre chapitre</label><br />
                    <input type="text" id="title" name="title">
                </div>
                <div>
                    <label for="content">Texte</label><br />
                    <textarea id="#mytextarea" name="content"></textarea>
                </div>
                <div>
                    <label for="file">Fichier (tous formats | max. 1 Mo) :</label><br />
                    <input type="file" name="file" id="file" /><br />
                </div>
                <div>
                    <button class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-floppy-saved"></span> Enregistrer</button>
                </div>
                </form>
            </section>
        </div>
        </section>
    </div>
    <script>
        $("#corp").click(function() {
            $("#soin_visage").addClass("hidden");
        });
        $("#visage").click(function() {
            $("#soin_visage").removeClass("hidden");
        });
    </script>
</body>