<?php
    if ($flash==true)
    {?> 
        <div class="alert alert-success alert-dismissable col-lg-12">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <?php 
        $set = $req->showFlash();
        ?>  
        </div> 
    <?php }
?>

<body>
    <div class="container">
        <header class="page-header">
            <h1>How she did</h1>
        </header>

        <section class="row">
        <div class="col-sm-12">


        <p><a href ="index.php"> Retour à la liste des articles </a></p>

        <br><br>
        <h2> Mes articles </h2>
        <?php
        while ($data=$articles-> fetch())
        {
        ?>
        
            <section class="col-sm-offset-1 col-sm-8 table-responsive">
                <table class="table table-bordered table-striped table-condensed">
                <tr>
                    <td>
                    <?php echo $data['title']; ?>
                    </td>

                    <td>
                    le <?=$data['article_date_fr']; ?>
                    </td>

                    <td>
                    <form action="index.php?action=editArticle&amp;id=<?= $data['id'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-info"><span class="glyphicon glyphicon-pencil"></span> Modifier</button>
                    </form></td>

                    <td><form action="index.php?action=removeArticle&amp;id=<?= $data['id'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span> Supprimer</button>
                    </form></td>
                </tr>
                </table>
            </section>

        <?php
        }
        $articles->closeCursor();
        ?>
        <br>
            <section class="col-sm-10">
                <h2 class="ajout"> Ajouter un nouvel article </h2>

                <form action='index.php?action=addArticle' method='post' enctype='multipart/form-data'>
                    
                <div>
                    <label for="title">Titre chapitre</label><br />
                    <input type="text" id="title" name="title">
                </div>
                <div>
                    <label for="content">Texte</label><br />
                    <textarea id="#mytextarea" name="content"></textarea>
                </div>
                <div>
                    <label for="file">Fichier (tous formats | max. 1 Mo) :</label><br />
                    <input type="file" name="file" id="file" /><br />
                </div>
                <div>
                    <label for="file">Fichier (tous formats | max. 1 Mo) :</label><br />
                    <input type="file" name="file2" id="file2" /><br />
                </div> 
                <div>
                    <button class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-floppy-saved"></span> Enregistrer</button>
                </div>
                </form>
            </section>
        </br>
        <br><br>
        <section class="row">
        <div class="col-sm-12">
        <h2> Mes articles de ma trousse </h2>
        <?php
        $data2=$articlesTrousse->fetchAll();
        foreach ($data2 as $data1)
        {
        ?>
            <section class="col-sm-offset-1 col-sm-8 table-responsive">
                <table class="table table-bordered table-striped table-condensed">
                <tr>
                    <td>
                    <?php echo $data1['title_article_trousse']; ?>
                    </td>

                    <td>
                    le <?php $data1['article_date_fr']; ?>
                    </td>

                    <td>
                    <form action="index.php?action=editArticleTrousse&amp;id=<?= $data1['id_article_trousse'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-info"><span class="glyphicon glyphicon-pencil"></span> Modifier</button>
                    </form></td>

                    <td><form action="index.php?action=removeArticleTrousse&amp;id=<?= $data1['id_article_trousse'] ?>" method="POST"/>
                    <button class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span> Supprimer</button>
                    </form></td>
                </tr>
                </table>
            </section>
        <?php
        }
        $articlesTrousse->closeCursor();
        ?>
        </br>
            <section class="col-sm-10">
                <h2 class="ajout"> Ajouter un article dans ma trousse </h2>

                <form action='index.php?action=addArticleTrousse' method='post' enctype='multipart/form-data'>
                    
                <div>
                    <label for="title">Titre chapitre</label><br />
                    <input type="text" id="title" name="title">
                </div>
                <div>
                    <label for="content">Texte</label><br />
                    <textarea id="#mytextarea" name="content"></textarea>
                </div>
                <div>
                    <label for="file">Fichier (tous formats | max. 1 Mo) :</label><br />
                    <input type="file" name="file" id="file" /><br />
                </div>
                <div>
                    <button class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-floppy-saved"></span> Enregistrer</button>
                </div>
                </form>
            </section>
        </div>
        </section>
    </div>
</body>