<?php
if ($flash==true)
{?> 
    <div class="alert alert-success alert-dismissable col-lg-12">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <?php
    $set = $req->showFlash();
    ?> 
    </div> 
<?php }
?>
    <div class="container">
        <header class="page-header">
            <h1>How she did</h1>
        </header>

        <section class="row">

        <div class="col-sm-12">

        <p><a href ="index.php?action=articles"> Retour à la liste des articles </a></p>

        	<div class="row">

                <section class=" col-sm-12 text-center">
                    <div class="col-sm-12">
                        <h3>
                           <?php echo $article['title'] ?>
                           <em>le <?php echo $article['article_date_fr'] ?></em>
                        </h3>
                        <?php 
                        if($article['file']){
                            echo '<img src="images/'.$article['file'].'" class="image width-100" alt="image" style="position:relative"/>';
                        } 
                        if($article['file2']){
                            echo '<img src="images/'.$article['file2'].'" class="image2 width-100" alt="image2" style="position:absolute; top:300px; left:150px"/>';
                        }?>
                        <?php echo $article['content'] ?>
                    </div>
                </section>
            </div>
        </div>
        </section>
    </div>
    
    <div class="container text-center">
        <h3 id = "showComments"> Voir les commentaires </h3>
        <div class="wrap hidden" id="commentShowed">
            <?php
                    while ($data=$comments-> fetch())
                {
                ?>
                    <div class="news"/>
                        <h4>
                        <?php echo $data['author'] ?>
                        le <?= $data['creation_date_fr'] ?>
                        </h4>

                        
                        <?php echo '<span class="text-center" id="commentContent">'.$data['content'].'</span>'?>
                        
                    </div>

                    <form action="index.php?action=signaledComment&amp;id=<?= $data['id'] ?>" method='post'>
                        <input type="hidden" name="id" value="<?=$article['id']?>"/> 
                    <button class="btn btn-xs btn-warning" type="submit"><span class="glyphicon glyphicon-warning-sign"></span> Signaler</button>
                    </form>

                <?php
                }
                $comments->closeCursor();
                ?>

                        <h5> Ajouter un nouveau commentaire </h5>

                        <form action="index.php?action=addComment&amp;id=<?= $data['id'] ?>" method='post'>

                            <input type="hidden" name="id" value="<?=$article['id']?>"/>    

                            <div>
                                <label for="author">Votre pseudo</label><br />
                                <input type="text" id="author" name="author">
                            </div>

                            <div>
                                <label for="content">Texte</label><br />
                                <textarea id="content" name="content"></textarea>
                            </div>

                            <div>
                                <button class="btn btn-primary btn-success"><span class="glyphicon glyphicon-chevron-down"></span> Envoyer</button>
                            </div>
                        </form>
        </div>
    </div>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
	<div class="row mobile-social-share">
            <div class="col-md-9">
                <h3>Partager l'article</h3>
            </div>
            <div id="socialHolder" class="col-md-3">
                <div id="socialShare" class="btn-group share-group">
                    <a data-toggle="dropdown" class="btn btn-info">
                        <i class="fa fa-share-alt fa-inverse"></i>
                    </a>
                    <button href="#" data-toggle="dropdown" class="btn btn-info dropdown-toggle share">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a data-original-title="Twitter" rel="tooltip"  href="https://twitter.com/login?lang=fr" class="btn btn-twitter" data-placement="left">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a data-original-title="Facebook" rel="tooltip"  href="https://www.facebook.com/" class="btn btn-facebook" data-placement="left">
                                    <i class="fa fa-facebook"></i>
                            </a>
                        </li>					
                        <li>
                            <a data-original-title="Google+" rel="tooltip"  href="https://plus.google.com/" class="btn btn-google" data-placement="left">
                                    <i class="fa fa-google-plus"></i>
                            </a>
                        </li>
                        <li>
                            <a data-original-title="LinkedIn" rel="tooltip"  href="https://www.linkedin.com" class="btn btn-linkedin" data-placement="left">
                                    <i class="fa fa-linkedin"></i>
                            </a>
                        </li>
                        <li>
                            <a data-original-title="Pinterest" rel="tooltip"  href="https://www.pinterest.fr/" class="btn btn-pinterest" data-placement="left">
                                <i class="fa fa-pinterest"></i>
                            </a>
                        </li>
                        <li>
                            <a  data-original-title="Email" rel="tooltip" class="btn btn-mail" data-placement="left">
                                <i class="fa fa-envelope"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
	</div>
</div>
    <script>
        $("#showComments").click(function() {
            $("#commentShowed").removeClass("hidden");
        });
    </script>
