<body>
    <header class="page-header">
        <h1>How she did</h1>
    </header>

<div class="col-sm-11 container1">
    <section class="row1">
        <div class="col-sm-12">
            <?php
            $datas1=$articles-> fetchAll();
            $data2 = array_slice($datas1, 0,2);
            foreach ($data2 as $data)    
            {
            ?>
                <div class="col-xs-12 col-sm-6 news text-center"/>
                    <?php
                    if($data['file']){
                        echo '<img src="images/'.$data['file'].'" class="image width-100" alt="image" style="position:relative"/>';
                    } 
                    ?> 
                    </br></br>
                    <strong>
                    <?php
                    echo $data['title']; ?>
                    </strong>
                    </br>
                    <a href="index.php?action=article&amp;id=<?= $data['id'] ?>">Lire la suite...</a>
                </div>
            <div class="col-sm-1 vl"></div>
            <?php
            }
            $articles->closeCursor();
            ?>
        </div>
    </section>
    
    <section class="row1">
        <div class="col-sm-12">
            <?php
            $data3 = array_slice($datas1, 2);
            foreach ($data3 as $data)    
            {
            ?>
                <div class="col-xs-12 col-sm-4 news text-center"/>
                 </br> </br> </br> </br> </br> </br> </br>
                    <?php
                    if($data['file']){
                        echo '<img src="images/'.$data['file'].'" class="image1 width-100" alt="image" style="position:relative"/>';
                    } 
                    ?> 
                    </br></br>
                    <strong>
                    <?php
                    echo $data['title']; ?>
                    </strong>
                    </br>
                    <a href="index.php?action=article&amp;id=<?= $data['id'] ?>">Lire la suite...</a>
                    <div class="col-sm-1 vl2"></div>
                </div>
            
            <?php
            }
            $articles->closeCursor();
            ?>
        </div>
    </section>
</div>
    
    </br>
</body>