<?php
/*if ($flash==true)
{?> 
    <div class="alert alert-success alert-dismissable col-lg-12">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <?php
    $set = $req->showFlash();
    ?> 
    </div> 
<?}*/
?>
<body>    
    <div class="container">
        <header class="page-header">
            <h1>Billet simple pour l'Alaska</h1>
        </header>

        <section class="row">

        <div class="col-sm-12">

        <p><a href ="index.php"> Retour à la liste des chapitres </a></p>

        	<div class="row">

                <section class="col-sm-offset-2 col-sm-8">

            	   <h3>
            	       <?php echo $article['title'] ?>
            	       <em>le <?php echo $article['article_date_fr'] ?></em>
            	   </h3>

            	   <p><?php echo $article['content'] ?></p>
                </section>
            </div>

    	
        </div>
        </section>
    </div>
</body>
