<body>
    <header class="page-header">
        <h1>How she did</h1>
    </header>

<div class="col-sm-11 container">
        <section class="row1">
            <div class="col-sm-12">
                <?php
                $datas1=$articlesTrousse-> fetchAll();
                foreach ($datas1 as $data)    
                {
                ?>
                    <div class="col-sm-3 news text-center" style="margin-right: 15px; margin-top: 15px; margin-bottom: 15px"/>
                        <?php
                        if($data['file_article_trousse']){
                            echo '<img src="images/'.$data['file_article_trousse'].'" class="image1 width-100" alt="image" style="position:relative"/>';
                        } 
                        ?> 
                        </br>
                        <strong>
                        <?php
                        echo $data['title_article_trousse']; ?>
                        </strong>
                        </br>
                        <?php $res=$data['content_article_trousse'];
                        $res=substr($res, 0, 40);
                        echo $res; ?>
                        <a href="index.php?action=articleTrousse&amp;id=<?= $data['id_article_trousse'] ?>">Lire la suite...</a>
                    </div>
                <?php
                }
                $articlesTrousse->closeCursor();
                ?>
            </div>
        </section>
    </div>
    
    </br>
</body>