<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
        <script src="bootstrap/js/jquery.js"></script>
        <link href="framework/style.css" rel="stylesheet">
        <script src="bootstrap/js/bootstrap.js" rel="stylesheet"></script>        
    </head>

<body>
    <?php
        if ($flash==true)
        {?> 
            <div class="alert alert-success alert-dismissable col-lg-12">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <?php 
            $set = $req->showFlash();
            ?> 
            </div> 
        <?php }
    ?>
    <div class="container2">
      	<header>
            <div class="minview col-sm-12 col-lg-10">
        		<h1>Bienvenue sur l'interface administrateur</h1>
        	</div>
        </header>
        	<br><br>

            <section class="row2">
            	<div class="col-sm-12 col-lg-10">
        			<h2><p>Je me connecte</p></h2>
        		</div>

        		<section>
            	<div class="col-lg-12">
        			<form action='index.php?action=verifyController' method='POST'>

        			<p><label><strong>Identifiant</strong></label><input type="action" name="login"></p>
        			<p><label><strong>Mot de passe</strong></label><input type="password" name="pass"></p>
        			<button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-ok-sign"></span> Envoyer</button>

        			</form>
        		</div>
        	    </section>
            </section>
    </div>

    <div class="col-sm-12 col-lg-10">
    <p><a href ="index.php"> Retour à la liste des chapitres </a></p>
    </div>

</body>