<?php
    if ($flash==true)
    {?> 
        <div class="alert alert-success alert-dismissable col-lg-12">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <?php 
        $set = $req->showFlash();
        ?>  
        </div> 
    <?php }
?>

<body>
    <header class="page-header">
        <h1>How she did</h1>
    </header>
    
    <div class="col-sm-11 container">
        <section class="row1">
            <div class="col-sm-12">
                <?php
                $req=$articles-> fetchAll();
                $datas = array_slice($req, 0, 1);
                $datas1 = array_slice($req, 1);
                foreach ($datas as $data)    
                {
                ?>
                    <div class="col-sm-12 news text-center" style="margin-right: 15px; margin-top: 15px; margin-bottom: 15px"/>
                            <?php
                            if($data['file']){
                                echo '<img src="images/'.$data['file'].'" class="image width-100" alt="image" style="position:relative"/>';
                            } 
                            if($data['file2']){
                                echo '<img src="images/'.$data['file2'].'" class="image2 width-100" alt="image2" style="position:absolute; top:250px; left:350px"/>';
                            } ?> 
                        <div style="position:absolute; top:40px; right: 200px">
                            <strong>
                            <?php
                            echo $data['title']; ?>
                            </strong>
                            </br>
                            <?php $res=$data['content'];
                            $res=substr($res, 0, 40);
                            echo $res; ?>
                            <a href="index.php?action=article&amp;id=<?= $data['id'] ?>">Lire la suite...</a>
                        </div>
                    </div>
                <?php
                }
                $articles->closeCursor();
                ?>
            </div>
        </section>
    </div>
    
    <div class="col-sm-12 container">
        <section class="row1">
            <div class="col-sm-12">
                <?php
                foreach ($datas1 as $data)    
                {
                ?>
                    <div class="col-sm-3 news text-center" style="margin-right: 15px; margin-top: 15px; margin-bottom: 15px"/>
                        <?php
                        if($data['file']){
                            echo '<img src="images/'.$data['file'].'" class="image1 width-100" alt="image" style="position:relative"/>';
                        } 
                        ?> 
                        </br>
                        <strong>
                        <?php
                        echo $data['title']; ?>
                        </strong>
                        </br>
                        <?php $res=$data['content'];
                        $res=substr($res, 0, 40);
                        echo $res; ?>
                        <a href="index.php?action=article&amp;id=<?= $data['id'] ?>">Lire la suite...</a>
                    </div>
                <?php
                }
                $articles->closeCursor();
                ?>
            </div>
        </section>
    </div>
    </br>
    <div class="col-sm-12 container">
        <section class="row1">
            <div class="col-sm-12">
                 <?php
                $req1=$articlesTrousse-> fetchAll();
                $req12 = array_slice($req1, 0, 3);
                foreach ($req12 as $datas)    
                {
                ?>
                    <div class="col-sm-3 news text-center" style="margin-right: 15px; margin-top: 15px; margin-bottom: 15px"/>
                        <?php
                        if($datas['file_article_trousse']){
                            echo '<img src="images/'.$datas['file_article_trousse'].'" class="image3 width-100" alt="image" style="position:relative"/>';
                        } 
                        ?> 
                        </br>
                        <strong>
                        <?php
                        echo $datas['title_article_trousse']; ?>
                        </strong>
                        </br>
                        <?php $res=$datas['content_article_trousse'];
                        $res=substr($res, 0, 40);
                        echo $res; ?>
                        <a href="index.php?action=articleTrousse&amp;id=<?= $datas['id_article_trousse'] ?>">Lire la suite...</a>
                    </div>
                <?php
                }
                $articlesTrousse->closeCursor();
                ?>
            </div>
        </section>
    </div>
</body>