<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr">

    <head>
        <meta charset="UTF-8">
        <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
        <script src="bootstrap/js/jquery.js"></script>
        <link href="framework/style.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="bootstrap/js/bootstrap.js" rel="stylesheet"></script>
        <script type="text/javascript" src="tinymce/js/tinymce/tinymce.js"></script>
        <script src="http://code.jquery.com/jquery.js"></script>
        <script type="text/javascript">
            tinyMCE.init({
                    selector : 'textarea',
                    plugins : 'code image',
                    height : '800',
                    toolbar : 'indo redo | image code',
                    image_class_list: [
                        {title: 'None', value: 'images'}
                      ],
                    images_upload_url: 'upload.php',
                    images_upload_handler: function (blobInfo, success, failure) {
                            var xhr, formData;

                            xhr = new XMLHttpRequest();
                            xhr.withCredentials = true;
                            xhr.open('POST', 'upload.php');

                            xhr.onload = function() {
                                var json;

                                if (xhr.status !== 200) {
                                    failure('HTTP Error: ' + xhr.status);
                                    return;
                                }

                                json = JSON.parse(xhr.responseText);

                                if (!json || typeof json.location !== 'string') {
                                    failure('Invalid JSON: ' + xhr.responseText);
                                    return;
                                }

                                success(json.location);
                            };

                            formData = new FormData();
                            formData.append('file', blobInfo.blob(), blobInfo.filename());

                            xhr.send(formData);
                        },
                    images_dataimg_filter: function(img) {
                        return img.hasAttribute('internal-blob');
                    },
                language : "fr",
                add_unload_trigger : false,
                remove_linebreaks : false,
                inline_styles : false,
                convert_fonts_to_spans : false,
                forced_root_nlock : false,
                forced_br_newlines : true,
                forced_p_newlines : true
            });
        </script>
        <script src="bootstrap/js/jquery.js"></script>
        <title><?= $title ?></title>
        
    </head>
        
    <body>
        
        <div class="col-sm-12 container">
        <header>
            <nav class="navbar blog pull-right">
                <div class="collapse navbar-collapse" id="navbarNav" style="padding:0; padding-top:15px">
                    <a class="nav-link" style="margin-right:15px" href="index.php">Accueil<span class="sr-only">(current)</span></a>
                    <a class="nav-link"style="margin-right:15px" href="index.php?action=articles">Articles</a>
                    <a class="nav-link" style="margin-right:22px" href="index.php?action=articlesTrousse">Ma trousse</a>
                    <a class="nav-link" href="#"><span class="glyphicon glyphicon-search" id="icon_rechercher"></a>
                    <form action='index.php?action=search' method='post'>
                        <div class="input-group" id="rechercher">
                            <input type="text"  name="rechercher">
                            <input class="btn btn-primary btn-sm" value="OK" type="submit" name="submit" id="envoyer">
                        </div>
                    </form>
                </div>
            </nav>
            <nav class="navbar blog-nav pull-right">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <a class="nav-link" style="margin-bottom:20px" href="#" id="reseauxSociaux">R&eacuteseaux sociaux</a>
                    <a class="nav-link " href="#" id="aboutMe">A propos</a>
                </div>
            </nav>
        </header>
            
            <div class="col-sm-2 text-center fixed-social hidden" id="social">
                <button type="button" class="close" aria-label="Close" id="close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4>Rejoindre Lena</h4>
                <div class="socials">
                    <a data-original-title="Twitter" rel="tooltip"  href="https://twitter.com/login?lang=fr"  data-placement="left">
                        <i class="fa fa-twitter"></i>
                    </a>
                     &nbsp &nbsp
                    <a data-original-title="instagram" rel="tooltip"  href="https://www.instagram.com/?hl=fr" data-placement="left">
                            <i class="fa fa-instagram"></i>
                    </a>
                    &nbsp &nbsp
                    <a data-original-title="Facebook" rel="tooltip"  href="https://www.facebook.com/" data-placement="left">
                            <i class="fa fa-facebook"></i>
                    </a>
                   
                </div> 
                </br>
            </div>
            
            <div class="col-sm-12 hidden" id="about">
                <section class="col-sm-12">
                    <button type="button" class="close2" aria-label="Close" id="close2">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h2>La beaut&eacute pour les asiatiques</h2>

                    <h4>Qui je suis?</h4>
                    <div class="col-sm-10">
                        <p class="about1"> Je suis Lena, je me suis rendu compte que pour nous les filles asiatiques, il y'avait tr&egraves peu de blog ou de conseil beaut&eacute pour notre typage aisatique, qui vous le verrez &agrave de nombreuses particularit&eacute et de a priori.
                        Je suis super contente de pouvoir partager avec vous mes exp&eacuteriences et essai, et j'esp&egravere vous guidera au mieux dans ce vaste monde de la beaut&eacute!</p>
                    </div>
                    <div class="col-sm-2" style="position:absolute; top:7px; right:10px">
                        <img src="images/004.jpg" class="image3 width-100" alt="image" style="position:relative"/>
                    </div>
                </section>
             </div>
        </div>

        <?php include $template.'View.phtml'; ?>

        <section class="footer col-sm-12">  
            <footer>
            <?php
            
            if ($logged==TRUE)
            { ?>
                <div class="col-sm-3">
                <a class="admin" href="index.php?action=deconnexion"> Deconnexion </a>
                </div>
                <div class="col-sm-offset-7 col-sm-2">
                <a class="admin" href="index.php?action=showAdmin"> Page admin </a>
                </div>
                
            <?php }
            
            if ($logged==FALSE)
            { ?>
                <a class="admin" href="index.php?action=connexion"> Connexion admin du site </a>
                
            <?php }
            ?>
            </footer>
        </section>
        
        <script>
            $("#reseauxSociaux").click(function() {
                $("#social").removeClass("hidden");
            });
            $("#close").click(function() {
                $("#social").addClass("hidden");
            });
            
            $("#aboutMe").click(function() {
                $("#about").removeClass("hidden");
            });
            $("#close2").click(function() {
                $("#about").addClass("hidden");
            });
            $("#icon_rechercher").ready(function() {
                $("#rechercher").addClass("hidden");
            });
            $("#icon_rechercher").click(function() {
                $("#rechercher").removeClass("hidden");
            });
        </script>
        
    </body>

</html>
