<?php
    if ($flash==true)
    {?> 
        <div class="alert alert-success alert-dismissable col-lg-12">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <?php 
        $set = $req->showFlash();
        ?>  
        </div> 
    <?php }?>

<body>
    <header class="page-header">
        <h1>How she did</h1>
    </header>
    
    <p><a href ="index.php?action=showAdmin"> Retour à la liste des articles </a></p>
    
    <section class="col-sm-10">
        <h2 class="ajout"> Ajouter un nouvel article </h2>

        <form action='index.php?action=addArticle' method='post' enctype='multipart/form-data'>

            <div>
                <label for="title">Titre chapitre</label><br />
                <input type="text" id="title" name="title">
            </div>
            <div>
                <label for="content">Texte</label><br />
                <textarea id="#mytextarea" name="content"></textarea>
            </div>
            <div>
                <label for="file">Fichier (tous formats | max. 1 Mo) :</label><br />
                <input type="file" name="file" id="file" /><br />
            </div>
            <div>
                <label for="file">Fichier (tous formats | max. 1 Mo) :</label><br />
                <input type="file" name="file2" id="file2" /><br />
            </div> 
            <div>
                <button class="btn btn-primary btn-primary"><span class="glyphicon glyphicon-floppy-saved"></span> Enregistrer</button>
            </div>
        </form>
    </section>
</body>