<body>   
    <div class="container text-center">
        <header class="page-header">
            <h1>How she did</h1>
        </header>
        <div class="col-sm-12" id="commentShowed">
            <section class="col-sm-offset-1 col-sm-10 table-responsive">
                <ul>
                    <?php 
                    foreach ($searchResults as $data)
                    { ?>
                        <li>
                            <?php echo $data['title']; 
                            $res=$data['content'];
                            $res=substr($res, 0, 150);
                            echo $res;?>
                            <a class="more" style="font-style: italic;" href="index.php?action=article&amp;id=<?= $data['id'] ?>">Lire la suite...</a>
                            <hr>
                        </li>
                    <?php }
                    $searchResults->closeCursor();
                    ?>
                </ul>
            </section>
        </div>
    </div>
</body>  